version: '3'
services:
    #PHP Service
    app-1:
        build:
            context: .
            dockerfile: Dockerfile
        command: ["php", "artisan", "octane:start", "--port=8000", "--host=0.0.0.0"]
        container_name: app-1
        volumes:
            - ./:/var/www
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '2816MB'
    app-2:
        build:
            context: .
            dockerfile: Dockerfile
        command: ["php", "artisan", "octane:start", "--port=8000", "--host=0.0.0.0"]
        container_name: app-2
        volumes:
            - ./:/var/www
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: '2816MB'
    #Nginx Service
    load-balancer:
        image: nginx:alpine
        container_name: load-balancer
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - app-network
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: '512MB'
    #MongoDB Service
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - dbdata:/data/db
        networks:
            - app-network
        environment:
            MONGO_INITDB_DATABASE: vehicle
        deploy:
            resources:
                limits:
                    cpus: '1.5'
                    memory: '2048MB'

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
